blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('post/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('review/<int:pk>/', views.AddComments.as_view(), name='add_comments')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse




class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    short_title = models.CharField(max_length=50)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    image = models.ImageField(upload_to='post_images/')


    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'


    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return f'{self.title}, {self.author}'


    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class Comments(models.Model):
    text_comments = models.TextField('Текст комментария,', max_length=2000)
    email = models.EmailField()
    user_name = models.CharField('Имя пользователя', max_length=20)
    post = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE  )

    def __str__(self):
        return f'{self.text_comments}, {self.post}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

blog/views.py
from django.shortcuts import render, redirect
from blog.models import Post
from django.views.generic.base import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .form import CommentsForm
from django.urls import reverse
from django.contrib.auth import login



def index(request):
    posts = Post.objects.all()
    posts_per_page = 10
    paginator = Paginator(posts, posts_per_page)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/src/index.html', {'posts': posts})


def about(request):
    return render(request, 'blog/src/about-us.html')


class PostDetail(View):
    def get(self, request, pk):
        post = Post.objects.get(id=pk)
        return render(request, 'blog/src/post_detail.html', {'post': post})


class AddComments(View):
    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = pk
            form.save()
        return redirect(reverse('post_detail', args=[pk]))

blog/templates/blog/src/about-us.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ post.title }}</title>
    <link rel="stylesheet" href="../../../static/blog/css/style.css">
</head>
<body>
    
    <header>
    <a href="{% url 'index' %}">
        <img style='height: auto;' src="../../../static/blog/image/logo.png" alt="Изображение логотипа" width="100" height="150" class="logo">
    </a>
    </header>


    <div class="block-about-us-parent">
        <div class="block-about-us">
            <h4 style="text-align: center;color: white;font-size: 20px">Exp это...</h4>
            
        </div>
    </div>
</body>
</html>

blog/templates/blog/src/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exp</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
</head>
<body>

    <nav>
        <ul>
            <li><a class="about-us" href="{% url 'about' %}">О нас</a></li>
            <li><a class="telegramm" href="https://t.me/ExpKurs_Bot">Телеграмм</a></li>
        </ul>
    </nav>
    <header>
    <a href="{% url 'index' %}">
        <img style='height: auto;' src="../../../static/blog/image/logo.png" alt="Изображение логотипа" width="100" height="150" class="logo">
    </a>
    </header>
    <div class="parent-div-url">
        <div class="block-url">

        </div>
    </div>
    <div class="parent-div-two">
        <div class="div-two">
            {% for post in posts %}
                    <h1><a href="{{ post.get_absolute_url }}" class="post-title">{{ post.title }}</a></h1>
                    <p class="short-title">{{ post.short_title }}</p>
                    <a href="#"><img src="{{ post.image.url }}"  alt="{{ post.title }}" style="width: 200px" class="image-post"> </a>
            {% endfor %}
    <div class="pagination">
        <span class="step-links">
        {% for i in posts.paginator.page_range %}
            {% if posts.number == i %}
                <span class="current">{{ i }}</span>
            {% else %}
                <a href="?page={{ i }}"style="padding-right: 3px">{{ i }}</a>
            {% endif %}
        {% endfor %}
            </span>
    </div>

            </span>
        </div>
        </div>
    </div>






</body>
</html>

blog/templates/blog/src/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ post.title }}</title>
    <link rel="stylesheet" href="../../../static/blog/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>

    <header>
    <a href="{%   url 'index'  %}">
        <img style='height: auto;' src="../../../static/blog/image/logo.png" alt="Изображение логотипа" width="100" height="150" class="logo">
    </a>
    </header>


    <div class="block-about-us-parent">
        <div class="block-about-us">
            <a href="#"><img src="{{ post.image.url }}"  alt="{{ post.title }}" style="width: 400px;" class="detail-photo"> </a>
                <h2 class="post-title"> {{ post.title }}</h2>
                    <a class="post-text">{{ post.text }}</a>
                        <a class="post-author">{{ post.author }}</a>
                <div class="comments">
                    <div>
                        <form action="{% url 'add_comments' post.id %}" method="post">
                            {% csrf_token %}
                            <div class="commments-you">
                                <a style="padding-bottom: 10px">Оставить комментарий</a>
                                <label>Ваше имя</label>
                                <input style="width: 50px" type="text" name="user_name">
                                <label>Ваш email</label>
                                <input style="width: 250px" type="email" name="email">
                                <label style="color:white"> Ваш комментарий</label>
                                <textarea name="text_comments"></textarea>
                            </div>
                            <div class="sumbit-button">
                                <button type="submit">
                                    <i class="fa-solid fa-paper-plane" style="color:black;"></i>
                                </button>
                            </div>
                        </form>
                         <div>
                {% for comment in post.comments_set.all %}
                    <div class="view-comment">
                        <div>
                            <h3 style="color: white;margin-bottom: 15px;padding-left: 10px">{{ comment.user_name }}</h3>
                            <div>
                                <p style="margin-top: 0px;padding-left: 10px">
                                    {{ comment.text_comments }}
                                </p>
                            </div>
                        </div>



                    </div>
                {% endfor %}
            </div>
                </div>
            </div>
        </div>
    </div>

<script>

</script>
</body>
</html>